name: dan
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Standard Flutter dependencies
  cupertino_icons: ^1.0.8
  pdf: ^3.10.0
  excel: ^2.1.0
  file_picker: ^8.1.7
  intl: ^0.18.0

  # Additional packages
  provider: ^6.0.0
  supabase_flutter: ^1.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  image: ^4.1.3
  win32: ^5.0.0
  ffi: ^2.1.0
  crypto: ^3.0.6
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/symbole.png
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
